repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-toml
      - id: check-yaml
        files: .y[a]?ml$
      - id: check-added-large-files
        args:
          - --maxkb=1000
      - id: check-json
      - id: check-merge-conflict
